import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";

import Navbar from "@/app/ui/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <div className="flex p-6 bg-green-900 min-h-screen text-white justify-center">
          <section className="" id="nav">
            <Navbar />
          </section>
          <section className="w-5/12 border border-solid border-gray-800 p-2" id="content">
            {children}
          </section>
          <section className="" id="search">
            <div className="sticky top-16">
              Search bar lol
            </div>
          </section>
        </div>

      </body>
    </html>
  );
}
